### ISSUE TITLE
Add shorcut search to command line history

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#19]
Is useful to reuse old searches, but nowadays it is not stored in command line history

**Comment by amerlyq** [comment]
Good idea, bad suggestion.
Storing all searches triggered by mappings will obstruct commands history, as main purpose of commands history -- storing manually entered commands. When doing searches and according to results applying all kind of shell filters / vim commands -- than search history is last thing you want to see when doing `<C-p>`.
Besides, there are `colder/cnewer` for default `Ag*`... So it's only `AgGroup` problem.
It could be better to implement this on foundation of `AgRepeat`, storing list of last N executed cmdlines. Then this list can be shown on `AgShowHistory [<N>]` to show (or choose and execute) menu with entries similarly to default vim. Or -- much better, but independent/supplementary idea -- to provide `Unite` sources for them -- to execute/yank/cmd_insert.
Also, I thought about using `v:count` with `AgRepeat` to specify relative index in this history, but you already utilized it for `ag -C`. Let's discuss it how better to distribute controls and commands.

**Comment by albfan** [comment]
I will describe my motivation to open this issue with a complete case and discuss different approaches.

**Comment by albfan** [comment]
http://vimdoc.sourceforge.net/htmldoc/eval.html#histadd()

It will be enabled using an option, but in my opinion it must be enabled by default.

**Comment by amerlyq** [comment]
Alright, let's do it as option and then I will try to clarify cases when I need to disable it, working tightly with sources of embedded. Thereafter, for those cases optimal solution could be found in completely another plane.

**Comment by albfan** [comment]
Here is the patch, with a related test.

https://github.com/albfan/ag.vim/blob/e12b34ed291c2512b586fed286f011c3518df94c/t/01-aggroup.vader#L47

to ease CI, here history is active by default

https://github.com/albfan/ag.vim/blob/e12b34ed291c2512b586fed286f011c3518df94c/autoload/ag.vim#L14

**Comment by albfan** [comment]
On test I left commented lines I cannot make work (execution of normal keystrokes). Actual way is rather obscure, so I left them to understand function calls

**Comment by amerlyq** [comment]
You did something unexpected and strange inside testsuite.
See how it was implemented for `:Ag` in my branch.
https://github.com/albfan/ag.vim/blob/feature_args_derive/t/02-ag.vader
By the way, you have too naive `helper.vim` which don't provide necessary fixture independence.
See fixed in https://github.com/albfan/ag.vim/blob/feature_args_derive/t/helper.vim
I will cherry-pick it into `rfc_t_suite` and merge into master.

**Comment by albfan** [comment]
Seems correct, add it if you want, but try to match comments to issue. This is about history. You are reluctant to add shortcut search to history. Seen it implemented, how does it feel?

**Comment by amerlyq** [comment]
Don't know which issue I should match by that cherry-picked commit, which fixes `helper.vim`.
It wasn't referenced to any issue at that time, nor it is now.
You propose to create new issues for each such minor case and then rewrite their commit messages in history? Is it really has sense?
In my head it too much recalls with practices how to comment code -- if we use history rewriting anyway, than weren't it be cleaner to simply regroup commits in sensible branches, not squashed but ready for PR, and having sensible commit messages? Especially in cases, when commit does exactly what it called.

**Comment by albfan** [comment]
I remember a closed issue #29 which could fit. Anyway well commented commits are enough. You can push it directly, but in case you need to discuss, yes: go ahead and open an issue. Label it as duplicate is not a big pain, as find a comment inside an unrelated issue for some decision is. issues are cheap.

See this issue for example. There's an issue and a branch and a commit. Once we decide final implementation I will close issue and rebase work (maybe even squash commits) (I prefer it over non fast forward merges) If there's some change in future I will open another issue or reopen this (if I can remember it's existence) whatever add less noise.

**Comment by albfan** [comment]
I would rebase this commit as-is (adding shortcut searchs to history by default) Any downside about that?

Here is the scenario I told you on develop of terminator fork:

https://github.com/albfan/terminator
- Search for a i18n string on project:
  
  ```
  :AgGroup "Cambiar visibilidad"
  ```
- Look for context in english:
  
  ```
  :3AgGroup "Cambiar visibilidad"
  ```
- Search english text ("Toggle window visibility") on project with shortcut search (visual selection and `<Leader>ag`)
- Recover search from history and refine search only to `*/*.py` files.
- Other times refine search to glade files `*/*.glade`

After move around for some hack been able to redo all searches (even manually written or by shortcut)

This implementation allows all that features, can see a bad behaviour related to add searchs to history.

**Comment by amerlyq** [comment]
Alright, do it. As I said before, we can thought out something, when I will
have clear usecase, where it becomes cumbersome. Now I have only
incongruent feeling, therefore was complaining. But in such case it is
really faster to try out first. You may close when merge.

**Comment by albfan** [comment]
Great, no more time this morning. I will inform you when is done.

**Comment by amerlyq** [comment]
I found problems with histadd, which will be reasonably irritating not only
for me. I think you simply have too different workflow to trap in them.

Suppose we have created complex cmdline to execute by shell, or manually
crafted complex regex for Ag.
Then did 10 fast searches by mappings. How many times you think you need to
press C-p to execute that your own cmdline? You will disable option for
histadd immediately after one such try.

Backward situation: you did one-two searches by mappings, then manually
executed 10 crafted cmdlines. How many times you need C-p to repeat search?
No one will ever use this opportunity to repeat search from cmdline in
practice. Here it's too inconvenient.

These two cases are the very reason why I recommended to use completely
separate search history. Because it must not interfere with native vim
histories in any way and mess user workflow. If you want to use histadd
only to be able to edit previous searches -- then do it explicitly -- by
AgEditHistory 3 -- or something like that.

**Comment by albfan** [comment]
Have to try. I suppose history remove dups. If it doesn't implement that would be neccesary (maybe using history and redir). Anyway that's enough to change default from enable to disable. Change it then, please.

**Comment by amerlyq** [comment]
History de-duplication works by default, but isn't panacea either. 
Because if you will search different entries -- suppose you slightly adjust visual selection on each search invocation -- main problem remains the same. 
You can't deduplicate this sainly in general. History will be polluted.
I'm voting for separate history implementation as feature, touched in #30. 
Presumably on top of AgRepeat
https://github.com/albfan/ag.vim/blob/feature_args_derive/autoload/ag/bind.vim#L2

**Comment by albfan** [comment]
Oh, then for me it is exactly the desire functionality. I want to keep on kistory:
- AgGroup search
- AgGroup "function search"
- AgGroup "function search" *.c
- AgGroup "fuction search" _/_.h

Anyway don't mind to disable by default. I have documented also on help files.

**Comment by amerlyq** [comment]
Alright, lets it remain this way until alternative implementation will be available.
Then we try to compare and decide.

**Comment by amerlyq** [comment]
Alternative ideas related to history API crossed my mind, because both commands and mapping support arguments auto-derive.
IMPL: always make sure, that commands add entry to history and `<Plug>` mappings not.
Then user can choose which way to map keybindings -- through comm to support history or by silent `<Plug>`. If you want control all mappings at once, then by option you can choose whole set of such mappings inside `plugin/ag.vim`.

I think that way history feature will become more self-sufficient and robust.
As bonus you will be able to call from shell `vim -c 'AgGroup {patt}'` and get cmdline by `<C-p>`.
