### ISSUE TITLE
Compress options definition

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#33]
Make them more DRY, replace by dict and add initialization in cycle.

**Comment by amerlyq** [comment]
About ag version check for `--vimgrep`.
I think, that more robust way would be to discard all older versions, because their format is already well-known, instead of trying to guess all possible future formats.
Therefore when compressing I will replace this check by:

```
!split(system("ag --version"), "\_s")[2] =~ '\v0\.%(\d|1\d|2[0-4])%(.\d+)?'
```

**Comment by albfan** [comment]
This is neat and concise, but in order to contribute to upstream just increase the distance from codebases. This seems like a subtask needed to achieve some kind of complex new feature but without that feature.

User stories would help to defeat this kind of changes like:
- To have X feature we need to add forty parameters to plugin config
  - change initialization to simplify and extend easily

**Comment by amerlyq** [comment]
But it leaves opened question how to manage those user stories in currently available interface...

I know such changes diverge codebase from upstream more and more, but upstream development have staled long ago, and they were needed to move forward. We still can split+rebase+squash changes to create necessary small FB for PR. However, in the end all original the code will be completely rewritten. Seems like it's more simple to invite @losingkeys or whoever current maintainer again and again, so they could track activity and merge it completely with less friction. It's only dreams, though:)
