### ISSUE TITLE
Searchs on unsaved buffers

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#62]
detected on #57

ag.vim relays on native ag, which operates on disk content files. Any unsaved buffer change is hidden to native ag.

Best shot is to mimic gitgutter check for unsaved changes

https://github.com/airblade/vim-gitgutter/blob/62cfae461f5159749de4b9dfa9254e52cc9e0008/autoload/gitgutter/diff.vim#L35

For files untracked it can be done too. (using cat and simple diff)

After detect added an removed lines, is just a matter of add and offset to line navigation. Using quickfix window has the problem to not have control on search jump, so you need to process all results first. For AgGroup it can be a postprocess, applied only on matches  selected to jump into.

 @Numkil This is another great candidate for neovim asynchronous execution

**Comment by amerlyq** [comment]
Ah, I understand now. I save often, very often. Almost after each sequence
of edits. So never met that problem - when Ag don't show right matches for
current buffer.

**Comment by albfan** [comment]
Sure. I do autosave on most graphical editors I use. But when you find a wrong result navigation this comes as a smart solution.

Autosave? Maybe another neovim feature?

**Comment by amerlyq** [comment]
I think I wouldn't liked autosave. I tried it once week long to adapt and
catched myself on freezing and instinctively waiting part of second before
each autosave pattern time.

Therefore I now have :update bound in all modes to ",s". It allows save and
exit insert, etc, mostly like "jj". And I often end editing sequence of
10-20 presses by ",s" in normal.

Anyway it has nothing to do with ag.vim.
For problem mitigation I would suggest excluding currently opened buffers
from search by --ignore option or -G flag and pipe buffers to ag directly
and separately. However doing this will introduce unnecessary complexity
and will not solve problem of several vim copies with unsaved results.
Because if you don't save in one instance it seems other instances also can
have unsaved buffers?

Doing autosave before each search is very bad practice, because it can't
become smart enough for all corner cases either.

**Comment by amerlyq** [comment]
Therefore better would be leave ag and aggroup as they are and tweak
agbuffer and agbuffergroup commands to pipe opened buffers content through
them without saving.

**Comment by albfan** [comment]
Although is not typical use case, as we are developing a plugin for vim I think (and  it's just an opinion) we must deal with its internal behaviour as unsaved buffers. I guess people expect that from us.

I like to rely on third party plugins for aspects outside current plugin scope, but many maintainers don't

Offer a configurable solution about this (letting people to choose wether to use it or not) is a must, but not prioritary (maybe sonething well defined for interested ones to implement if the need it)

**Comment by albfan** [comment]
Although is not typical use case, as we are developing a plugin for vim I think (and  it's just an opinion) we must deal with its internal behaviour as unsaved buffers. I guess people expect that from us.

I like to rely on third party plugins for aspects outside current plugin scope, but many maintainers don't

Offer a configurable solution about this (letting people to choose wether to use it or not) is a must, but not prioritary (maybe sonething well defined for interested ones to implement if the need it)

**Comment by amerlyq** [comment]
Let's do one step a time and check concept of searching on unsaved buffers in #71. Blocked until then.
